### PR TITLE
Fix SV_DumpUser_f so it's usable

### PR DESCRIPTION
**Pull request by vvvjk2**
SV_GetPlayerByName() is really bad for finding a client.
I suggest making this change to find by client number instead so it's easier to use. Also, since Info_Print bugs sometimes, print the raw string as well.

### CODE REVIEW

**Comment by ouned** [comment]
I also noticed this when using it. Good idea @vvvjk2
But I don't see why to print the raw info since Info_Print simply shouldn't fail :D

**Comment by vvvjk2** [comment]
if you put very long values into cvars like color1, color2, cl_anonymous etc., it bugged up for me a few times when trying it. but meh, it probably doesn't happen a lot so it's ok i guess

**Comment by ouned** [comment]
hmm ioq3 didn't modify it.
If the infostring is broken Info_Print will obviously fail.

**Comment by ouned** [comment]
closing this as it is more of a workaround.

**Pull request closed without merging**
