### PR TITLE
Fixed compilation issue for ARM architecture

### PR DESCRIPTION
**Pull request by raphaelM-sudo**
Was not able to compile on ARM without those changes.

### CODE REVIEW

**Comment by Daggolin** [comment]
Thanks for the pull request!

I am not sure if this is just a display error on mobile devices, but it looks like your commit also changed the reference for the mvsdk submodule to a commit that is not publicly available on GitHub.

If this is actually the case it would be nice if you could rebase your branch to not contain the mvsdk change.

**Comment by raphaelM-sudo** [comment]
Hi, it also required a change in mvsdk and I messed up the pull request with the submodule. I will try to update the PR

**Comment by raphaelM-sudo** [comment]
Hi, yes I had troubles with the mvsdk submodule. The PR got messed up because there were also [changes](https://github.com/mvdevs/mvsdk/commit/6ae7b927bbd470b8a4bdaa339ca556e3173ff0b3) required in mvsdk for the ARM compilation issue to be resolved.
Feel free to commit the fix yourself.

**Comment by aufau** [comment]
Merged in d7f8f63c789b6e19b805bb472bcb4e1ea7882b0d

**Pull request closed without merging**
