### PR TITLE
Demos autorecord and new recording icon

### PR DESCRIPTION
**Pull request by entdark**
Demos always get recording, but never saved, so the disk space is safe.
But if a player called a command "saveDemo" then demos will be saved with the format presented in "cl_autoDemoFormat" cvar.
Each call of the command saves the current in-game timestamp, so the idea is to call the command on only the needed moments.
So if we called it at 0:07 then at 13:37 on ffa_ns_streets in 1.02 version then the demo will have the name "0007_1337_ffa_ns_streets.dm_15" by default.
Autorecording gets restarted each new round.
If a player forgot or had no chance to save the demo they are still able to find it in LastDemo folder or save it with "saveDemoLast" command.

And another feature: new DEMO recording icon similar to REC in cameras. It's placed in the left bottom corner.

### CODE REVIEW

**Comment by TriForceX** [comment]
13:37 lol
can u upload a screenshot of the recording icon? :smiley:

**Comment by entdark** [comment]
http://i.imgur.com/ODbeIbQ.png

**Comment by TriForceX** [comment]
what about if im recording while playing? the recording icon will be over my hp/ap status bar/numbers?

**Comment by entdark** [comment]
Yes, it is optional, 2much worries.

**Comment by TriForceX** [comment]
anyways, i like it :+1:

**Comment by TriForceX** [comment]
anyways, i like it :+1:  what about making the icon blinking?

**Comment by entdark** [comment]
Not going to do, but feel free do it yourself, prolly animmap shader will do the trick.
I did similar here:
https://github.com/entdark/jaMME/blob/master/codemp/client/cl_scrn.cpp#L408

**Pull request merged**
