### PR TITLE
Ability to handle entity rendering inside a qvm

### PR DESCRIPTION
**Pull request by raphaelmichl**

### CODE REVIEW

**Comment by ouned** [comment]
The idea is good but I don't like the name SVF_ANTI_WALLHACK because that's not really what it is (more like what it is used to in your case), right?

Also, we'd have to add it to the next API-Level

**Comment by raphaelmichl** [comment]
Ok, you can rename it to whatever you want. The reason why I did not name it like SVF_RAW_BROADCAST was that there is still an area and cluster check going on before the entity is added to the entity list, so it isn't raw either. One could create another var like SVF_DISABLE_AREA_CHECK and wrap those checks within another if clause, like so:

```
if ( ent->r.svFlags & SVF_BROADCAST || (e == frame->ps.clientNum) || (ent->r.broadcastClients[frame->ps.clientNum/32] & (1<<(frame->ps.clientNum%32))))
{
	SV_AddEntToSnapshot( svEnt, ent, eNums );
	continue;
}

if(!(ent->r.svFlags & SVF_DISABLE_AREA_CHECK)) {
			// ignore if not touching a PV leaf
	// check area
	if ( !CM_AreasConnected( clientarea, svEnt->areanum ) ) {
		// doors can legally straddle two areas, so
		// we may need to check another one
		if ( !CM_AreasConnected( clientarea, svEnt->areanum2 ) ) {
			continue;		// blocked by a door
		}
	}

	bitvector = clientpvs;

	// check individual leafs
	if ( !svEnt->numClusters ) {
		continue;
	}
	l = 0;
	for ( i=0 ; i < svEnt->numClusters ; i++ ) {
		l = svEnt->clusternums[i];
		if ( bitvector[l >> 3] & (1 << (l&7) ) ) {
			break;
		}
	}

	// if we haven't found it to be visible,
	// check overflow clusters that coudln't be stored
	if ( i == svEnt->numClusters ) {
		if ( svEnt->lastCluster ) {
			for ( ; l <= svEnt->lastCluster ; l++ ) {
				if ( bitvector[l >> 3] & (1 << (l&7) ) ) {
					break;
				}
			}
			if ( l == svEnt->lastCluster ) {
				continue;	// not visible
			}
		} else {
			continue;
		}
	}
}

// add it
if( !(ent->r.svFlags & SVF_RAW_BROADCAST)) SV_AddEntToSnapshot( svEnt, ent, eNums );
```

**Comment by Daggolin** [comment]
Nice idea, but there is no need for this flag as far as I can tell.
Unless you are explicitly using it for `SVF_PORTAL` it should do similar to `SVF_NOCLIENT`.
And if you are intending to combine it with `SVF_BROADCAST` to only send the entity to chosen clients you can use `snapshotIgnore` and `snapshotEnforce` to do similar.

**Comment by aufau** [comment]
Reading your commit messages it seems to me that what you really wanted to have is per-client snapshot control. We already have an API for this, the problem is we haven't documented it yet :/

**Comment by aufau** [comment]
Here is documentation of this MVAPI feature I mentioned: https://github.com/mvdevs/jk2mv/wiki/API-Level-1#mvapi_locate_game_data

I hope it is clear how to use it and I hope it can help you achieve your goal. if you have any doubts I'll try to explain it better here (or join us on discord or #jk2mv quakenet irc channel)

**Comment by ouned** [comment]
closing this as its already there

**Pull request closed without merging**
