### PR TITLE
New up+down input handling:

### PR DESCRIPTION
**Pull request by 76616c6172**
Prioritize up when both keys are held together.

### CODE REVIEW

**Comment by aufau** [comment]
I would like to know a reason for this change but tbh it's almost certainly not going to pass.

Firstly it's a change that players would feel and jk2mv aims to be replacement for original client, not alternative. Changes like this throw some ppl away because they want it to feel the same.

Secondly, you could do something similar for strafing: when you hold left and press right, switch to right instead of 0.
This little time when you change strafe direction and hold both keys pressed down is a major speed waster when doing strafe challenges.
Part of improving your strafing is reducing this time. Doing this in a client automatically would be unfair advantage over other players and we never want do this in jk2mv.

**Comment by 76616c6172** [comment]
I made this change to make skating more responsive. It's part of a physics mode inspired by Slash's movement in QC - which is based on crouch-sliding from Quake 4.

It also helps inputting crouch>jump into a wall-clip and avoiding low ceilings while strafing.
I can't think of a gameplay case where a player wouldn't want this behavior.

You're absolutely right about left/right input. This input handling is widely used by TF2 players, they call it "null-movement".
I prefer this behavior myself; out in the wild there are people using this in JK2 as well.
I'm surprised this isn't the default yet, seeing as you are a hardcore input responsiveness enthusiast!

Your concern with regards to fairness and cheating is valid. It is a gradient all the way from "Client Enhancement" to "Wallhack".
Is it unfair to vanilla JK2 clients to improve JK2MV performance and fps? What about cg_fovAspectAdjust? Strafehelpers? Personally, I don't view nicer input handling as cheating.

Naturally as maintainer of this project, it is up to you to decide where to draw that line.

**Comment by aufau** [comment]
So is it for a specific mod with crouch sliding? Or normal strafing?
Does it make it easier to make low jumps without a script? I like the idea of getting rid of mechanics that can be scripted, but it's really not what this project does - improving or changing mechanics of the game.

It sounds like something that would be best left to a mod, but it's impossible. Still don't see it becoming **default** because it will surely affect ppl used to old behaviour and we just don't do this.

Whether we could add it with a cvar - I don't know, I'll consult other maintainers. It's a thin line from going to "cheat" territory. jk2 cheats have these "improvements" or rather "helpers" too. Some parts of original game are hard mechanically and this is what they are supposed to be. does q3a defrag client/mod have these?

Improving fps (jk2mv doesn't improve fps on low power machines really. maybe it reduces cpu load a bit lowering heat and battery drain) is ok because basically everyone is expected to have jk2mp.exe in perfect conditions experience - this is the line. We have no business in penalising ppl with worse hardware. It's not any better than jk2mp.exe at stable fps.
fov/aspect changes are part of mvsdk. It's a mod and you can use it with jk2mp.exe or any backward-compatible client. jk2mv will use basejk on non-jk2mv server with sv_pure 1. strafe helpers are parts of mods too.

We're obviously ok with improving things that don't affect player performance like lower cpu load, faster load times, high res fonts etc.

**Comment by 76616c6172** [comment]
Q: So is it for a specific mod with crouch sliding? Or normal strafing?
A: Yess this change is to support a specific mod that cares about jumping seamlessly out of a crouch slide.

This specific change does not affect normal strafing, other than making it possible to chain bunyhops without letting go of crouch (which can make wallclipping easier)

**Comment by aufau** [comment]
Hey, so having received some input from other maintainer we've decided to reject the pull request.

As I wrote earlier it *could* be used for gaining unfair advantage over other players and there is no easy way to limit it to a specific mod. This is a line we don't want to cross in this project.

If you're making a mod that requires it, you can easily maintain a fork of JK2MV and keep it in sync with this repo. I think continuous integration scripts should make it easy to obtain binary releases for others.

Don't get discouraged, if you've got other ideas or code you'd like to see in jk2mv - let us know please.

**Pull request closed without merging**
